#!/usr/bin/env node
/**
 * Compliance Remediation Engine
 *
 * Reads an audit report and creates GitHub issues on non-compliant repos.
 *
 * Usage:
 *   node compliance/remediate.js <audit-report.json> [options]
 *
 * Options:
 *   --mode=issues      Create issues on failing repos (default)
 *   --mode=report      Print remediation plan only (dry run)
 *   --label=NAME       Label for created issues (default: compliance)
 */

const fs = require('fs');
const { execFileSync } = require('child_process');

function parseArgs(argv) {
  const args = { _: [] };
  for (const arg of argv.slice(2)) {
    if (arg.startsWith('--')) {
      const [key, val] = arg.slice(2).split('=');
      args[key] = val ?? true;
    } else {
      args._.push(arg);
    }
  }
  return args;
}

const DIMENSION_LABELS = {
  chittyconnect: 'ChittyConnect',
  chittybeacon: 'ChittyBeacon',
  chittycanon: 'ChittyCanon',
  chittyregister: 'ChittyRegister',
  chittyrouter: 'ChittyRouter',
  chittytrust: 'ChittyTrust/ChittyCert',
  health_endpoint: 'Health Endpoint',
};

function buildIssueBody(svcName, svcData) {
  const lines = [];
  lines.push('## Compliance Audit Findings');
  lines.push('');
  lines.push(`This issue was auto-generated by the ChittyOS ecosystem compliance audit.`);
  lines.push('');
  lines.push(`**Service:** ${svcName}`);
  lines.push(`**Tier:** ${svcData.tier ?? 'unset'}`);
  lines.push(`**Type:** ${svcData.type}`);
  lines.push('');
  lines.push('### Failing Checks');
  lines.push('');

  const failures = Object.entries(svcData.checks)
    .filter(([, c]) => c.status === 'fail');

  for (const [dim, check] of failures) {
    lines.push(`#### ${DIMENSION_LABELS[dim] || dim}`);
    lines.push(`**Status:** FAIL`);
    if (check.reason) lines.push(`**Reason:** ${check.reason}`);
    if (check.details && check.details.length > 0) {
      for (const d of check.details) {
        lines.push(`- ${d}`);
      }
    }
    lines.push('');
  }

  lines.push('### Remediation');
  lines.push('');
  lines.push('Run the compliance setup from chittyops:');
  lines.push('```bash');
  lines.push(`./setup-org-workflows.sh --repo=${svcData.repo}`);
  lines.push('```');
  lines.push('');
  lines.push('Or manually add the missing files/workflows per the [compliance guide](https://github.com/CHITTYOS/chittyops/blob/main/compliance/README.md).');
  lines.push('');
  lines.push('---');
  lines.push('*Auto-generated by `compliance/remediate.js`*');

  return lines.join('\n');
}

function createIssue(repo, title, body, label) {
  const tmpFile = `/tmp/compliance-issue-${Date.now()}.md`;
  try {
    fs.writeFileSync(tmpFile, body);
    const result = execFileSync('gh', [
      'issue', 'create',
      '-R', repo,
      '--title', title,
      '--body-file', tmpFile,
      '--label', label,
    ], { encoding: 'utf8', timeout: 15000 });
    return result.trim();
  } catch (err) {
    return `ERROR: ${err.message}`;
  } finally {
    try { fs.unlinkSync(tmpFile); } catch {}
  }
}

async function main() {
  const args = parseArgs(process.argv);
  const inputFile = args._[0];
  const mode = args.mode || 'report';
  const label = args.label || 'compliance';

  if (!inputFile) {
    console.error('Usage: node remediate.js <audit-report.json> [--mode=issues|report]');
    process.exit(1);
  }

  const report = JSON.parse(fs.readFileSync(inputFile, 'utf8'));

  let issueCount = 0;

  for (const [orgName, orgData] of Object.entries(report.organizations)) {
    for (const [svcName, svcData] of Object.entries(orgData.services)) {
      if (svcData.skipped || !svcData.active) continue;

      const failures = Object.entries(svcData.checks || {})
        .filter(([, c]) => c.status === 'fail');

      if (failures.length === 0) continue;

      const failDims = failures.map(([d]) => DIMENSION_LABELS[d] || d).join(', ');
      const title = `[Compliance] ${failures.length} failing check(s): ${failDims}`;

      console.log(`\n${svcData.repo}: ${failures.length} failures`);
      for (const [dim, check] of failures) {
        console.log(`  - ${DIMENSION_LABELS[dim]}: ${check.reason || 'failed'}`);
      }

      if (mode === 'issues') {
        const body = buildIssueBody(svcName, svcData);
        const result = createIssue(svcData.repo, title, body, label);
        console.log(`  Issue: ${result}`);
        issueCount++;
      }
    }
  }

  console.log(`\n--- Remediation ${mode === 'issues' ? 'Complete' : 'Plan'} ---`);
  console.log(`Issues ${mode === 'issues' ? 'created' : 'to create'}: ${issueCount}`);
}

main().catch(err => {
  console.error('Remediation failed:', err.message);
  process.exit(2);
});
