name: Compliance Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  compliance:
    uses: CHITTYOS/chittyops/.github/workflows/reusable-compliance-check.yml@main
    with:
      service_name: '{{SERVICE_NAME}}'
      tier: {{TIER}}
      check_health: {{CHECK_HEALTH}}
      domain: '{{DOMAIN}}'
